version: '3.3'
services:
    rabbitmq:
        ports:
            - '5672:5672'
            - '15672:15672'
        image: 'rabbitmq:3.11-management'
    
    mongo: # database
        image: mongo:latest # pull the mongo image from docker hub
        logging: 
            driver: none # disable logging
        ports:
            - '27017:27017'